USE SmartHome;

CREATE TABLE Users (
	Id INT NOT NULL AUTO_INCREMENT, 
	UserName VARCHAR(50),
	Password VARCHAR(255),
	FirstName VARCHAR(50),
	LastName VARCHAR(50),
	Email VARCHAR(100),
	TempDisplay VARCHAR(1) DEFAULT 'c',
	PRIMARY KEY (id)
	);
